INSERT INTO `homeschool`.`subjects`
(
    `subject_id`,
    `subject_name`,
    `grade_level`
)
VALUES
    (1,'Bible','1'),
    (2,'Seatwork','1'),
    (3,'Reading Circle - AM - 3 Giraffes','1'),
    (4,'Reading Circle - AM - 2 Monkeys','1'),
    (5,'Reading Circle - AM - 1 Elephants','1'),
    (6,'Phonics/Language','1'),
    (7,'Writing','1'),
    (8,'Arithmetic','1'),
    (9,'Reading Circle - PM - 3 Giraffes','1'),
    (10,'Reading Circle - PM - 2 Monkeys','1'),
    (11,'Reading Circle - PM - 1 Elephants','1'),
    (12,'Spelling/Poetry','1'),
    (13,'Combination Practice','1'),
    (14,'Activity Time','1'),
    (15,'Bible','2'),
    (16,'Seatwork','2'),
    (17,'Reading Circle - AM - 3 Owls','2'),
    (18,'Reading Circle - AM - 2 Frogs','2'),
    (19,'Reading Circle - AM - 1 Ducks','2'),
    (20,'Phonics/Language','2'),
    (21,'Writing','2'),
    (22,'Arithmetic','2'),
    (23,'Reading Circle - PM - 3 Owls','2'),
    (24,'Reading Circle - PM - 2 Frogs','2'),
    (25,'Reading Circle - PM - 1 Ducks','2'),
    (26,'Spelling/Poetry','2'),
    (27,'Combination Practice','2'),
    (28,'Activity Time','2');
