INSERT INTO `homeschool`.`user_subjects`
(
    `user_id`,
    `subject_id`,
    `last_modified`
)
VALUES
-- ewan
    (1,15,CURRENT_TIMESTAMP),
    (1,16,CURRENT_TIMESTAMP),
    (1,2,CURRENT_TIMESTAMP),
    (1,4,CURRENT_TIMESTAMP),
    (1,20,CURRENT_TIMESTAMP),
    (1,21,CURRENT_TIMESTAMP),
    (1,22,CURRENT_TIMESTAMP),
    (1,10,CURRENT_TIMESTAMP),
    (1,26,CURRENT_TIMESTAMP),
    (1,27,CURRENT_TIMESTAMP),
    (1,28,CURRENT_TIMESTAMP),
-- gwynnie
    (2,1,CURRENT_TIMESTAMP),
    (2,2,CURRENT_TIMESTAMP),
    (2,4,CURRENT_TIMESTAMP),
    (2,6,CURRENT_TIMESTAMP),
    (2,7,CURRENT_TIMESTAMP),
    (2,8,CURRENT_TIMESTAMP),
    (2,10,CURRENT_TIMESTAMP),
    (2,12,CURRENT_TIMESTAMP),
    (2,13,CURRENT_TIMESTAMP),
    (2,14,CURRENT_TIMESTAMP);
