INSERT INTO `homeschool`.`lesson_tasks`
(
  `description`,
  `assets`,
  `tags`,
  `lesson_id`,
  `workbook_id`
)
VALUES
  ("Memorization: Psalm 34:8-19 (combined passages from L 26-65)","","classwork",1,NULL),
  ("Lesson: 'Who Am I?' (review game)","","classwork",1,NULL),
  ("Watch Video","","video",1,NULL),
  ("AR: p 131","","seatwork",6,41),
  ("BF: p 52","","seatwork",6,1),
  ("LA: p 66","","seatwork",6,35),
  ("LS: p 66","","seatwork",6,36),
  ("SP: p 20","","seatwork",6,73),
  ("WT: Copy Spelling List 10","","seatwork",6,40),
  ("WT: Copy; write the before and after numbers by ones","need asset","seatwork",6,40),
  ("WT: Copy; write two words (not the clue word) for each special sound.","need asset","seatwork",6,40),
  ("WT: (in cursive)Write one row of each - Oliva, Peter, Rachel, Samuel, Taylor","need asset","seatwork",6,40),
  ("WT: (in cursive) Look unto me and be ye saved. Isaiah 45:22","need asset (display 101-200 counting chart appendix b)","seatwork",6,40),
  ("Watch Video","","video",6,NULL),
  ("Teacher's Choice","","seatwork",6,NULL),
  ("SAS: Read orally / check comprehension p 103-107","","classwork",11,8),
  ("SAS: Re-read / check comprehension p 100-108","","classwork",11,8),
  ("basement","","classwork",11,NULL),
  ("Watch Video","","video",11,NULL),
  ("SS: Read orally / check comprehension p 30-35","","classwork",16,20),
  ("Watch Video","","video",16,NULL),
  ("TT: Read orally / check comprehension p 49-52","","classwork",21,33),
  ("Watch Video","","video",21,NULL),
  ("Have minisheet ready.","","classwork",26,NULL),
  ("Watch Video","","video",26,NULL),
  ("CFF: Vv","","classwork",31,38),
  ("WP: p 70","","classwork",31,39),
  ("Watch Video","","video",31,NULL),
  ("AR: p 131-132","","classwork",36,41),
  ("Lesson 66 Speed Drill","","classwork",36,42),
  ("Watch Video","","video",36,NULL),
  ("HR: Read orally p 63","","classwork",41,12),
  ("TT: p 53","","classwork",41,52),
  ("Watch Video","","video",41,NULL),
  ("HR: Read orally p 106","","classwork",46,23),
  ("SS: p 36","","classwork",46,60),
  ("Watch Video","","video",46,NULL),
  ("SAS: Read orally / check comprehension p 108-116","","classwork",51,59),
  ("SAS: p 117","","classwork",51,59),
  ("Watch Video","","video",51,NULL),
  ("Watch Video","","video",56,NULL),
  ("Watch Video","","video",61,NULL),
  ("DGW: p 5","","classwork",66,76),
  ("Watch Video","","video",66,NULL);
