INSERT INTO `homeschool`.`subject_workbooks`
(
    `subject_id`,
    `description`,
    `abbreviation`
)
VALUES
    (2,"Bible Friends Activity Book","BF"),
    (3,"Aesop's Fables","AF"),
    (3,"Animals in the Great Outdoors","AO"),
    (3,"Down by the Sea","DS"),
    (3,"Fun with Pets","FP"),
    (3,"Kind and Brave","KB"),
    (3,"Primary Bible Reader","PBR"),
    (3,"Secrets and Surprises","SAS"),
    (3,"Stepping Stones","SS"),
    (3,"Strong and True","ST"),
    (3,"Tiptoes","TT"),
    (3,"Handbook for Reading","HR"),
    (4,"Aesop's Fables","AF"),
    (4,"Animals in the Great Outdoors","AO"),
    (4,"Down by the Sea","DS"),
    (4,"Fun with Pets","FP"),
    (4,"Kind and Brave","KB"),
    (4,"Primary Bible Reader","PBR"),
    (4,"Secrets and Surprises","SAS"),
    (4,"Stepping Stones","SS"),
    (4,"Strong and True","ST"),
    (4,"Tiptoes","TT"),
    (4,"Handbook for Reading","HR"),
    (5,"Aesop's Fables","AF"),
    (5,"Animals in the Great Outdoors","AO"),
    (5,"Down by the Sea","DS"),
    (5,"Fun with Pets","FP"),
    (5,"Kind and Brave","KB"),
    (5,"Primary Bible Reader","PBR"),
    (5,"Secrets and Surprises","SAS"),
    (5,"Stepping Stones","SS"),
    (5,"Strong and True","ST"),
    (5,"Tiptoes","TT"),
    (5,"Handbook for Reading","HR"),
    (6,"Language 1","LA"),
    (6,"Letters and Sounds 1","LS"),
    (6,"Letters and Sounds 1 Tests",""),
    (7,"Cursive Formation Flashcards","CFF"),
    (7,"Writing with Phonics 1","WP"),
    (7,"Cursive Writing Tablet","WT"),
    (8,"Arithmetic 1","AR"),
    (8,"Arithmetic 1 Tests / Speed Drills",""),
    (9,"Aesop's Fables","AF"),
    (9,"Animals in the Great Outdoors","AO"),
    (9,"Down by the Sea","DS"),
    (9,"Fun with Pets","FP"),
    (9,"Kind and Brave","KB"),
    (9,"Primary Bible Reader","PBR"),
    (9,"Secrets and Surprises","SAS"),
    (9,"Stepping Stones","SS"),
    (9,"Strong and True","ST"),
    (9,"Tiptoes","TT"),
    (10,"Aesop's Fables","AF"),
    (10,"Animals in the Great Outdoors","AO"),
    (10,"Down by the Sea","DS"),
    (10,"Fun with Pets","FP"),
    (10,"Kind and Brave","KB"),
    (10,"Primary Bible Reader","PBR"),
    (10,"Secrets and Surprises","SAS"),
    (10,"Stepping Stones","SS"),
    (10,"Strong and True","ST"),
    (10,"Tiptoes","TT"),
    (11,"Aesop's Fables","AF"),
    (11,"Animals in the Great Outdoors","AO"),
    (11,"Down by the Sea","DS"),
    (11,"Fun with Pets","FP"),
    (11,"Kind and Brave","KB"),
    (11,"Primary Bible Reader","PBR"),
    (11,"Secrets and Surprises","SAS"),
    (11,"Stepping Stones","SS"),
    (11,"Strong and True","ST"),
    (11,"Tiptoes","TT"),
    (12,"Spelling and Poetry 1","SP"),
    (14,"Art Projects 1","AP"),
    (14,"Community Helpers Activity Book","CH"),
    (14,"Discovering God's World","DGW"),
    (14,"Health, Safety, and Manners 1","HSM"),
    (14,"My America and My World","MA"),
    (15,"King James Bible",""),
    (16,"History, Science, Health 2 Activity Book","HSH"),
    (17,"Across the Meadow","AM"),
    (17,"All Kinds of Animals","AKA"),
    (17,"Fun with Friends","FF"),
    (17,"Growing Up around the World","GAW"),
    (17,"Growing Up in Early America","GEA"),
    (17,"Growing Up Where Jesus Lived","GJL"),
    (17,"Handbook for Reading","HR"),
    (17,"My New Name","MN"),
    (17,"Primary Bible Reader","PBR"),
    (17,"Quests for Adventure","QA"),
    (17,"Reading Comprehension 2 Skill Sheets","RC2"),
    (17,"Through the Skies","TS"),
    (17,"Wonders of Imagination","WI"),
    (18,"Across the Meadow","AM"),
    (18,"All Kinds of Animals","AKA"),
    (18,"Fun with Friends","FF"),
    (18,"Growing Up around the World","GAW"),
    (18,"Growing Up in Early America","GEA"),
    (18,"Growing Up Where Jesus Lived","GJL"),
    (18,"Handbook for Reading","HR"),
    (18,"My New Name","MN"),
    (18,"Primary Bible Reader","PBR"),
    (18,"Quests for Adventure","QA"),
    (18,"Reading Comprehension 2 Skill Sheets","RC2"),
    (18,"Through the Skies","TS"),
    (18,"Wonders of Imagination","WI"),
    (19,"Across the Meadow","AM"),
    (19,"All Kinds of Animals","AKA"),
    (19,"Fun with Friends","FF"),
    (19,"Growing Up around the World","GAW"),
    (19,"Growing Up in Early America","GEA"),
    (19,"Growing Up Where Jesus Lived","GJL"),
    (19,"Handbook for Reading","HR"),
    (19,"My New Name","MN"),
    (19,"Primary Bible Reader","PBR"),
    (19,"Quests for Adventure","QA"),
    (19,"Reading Comprehension 2 Skill Sheets","RC2"),
    (19,"Through the Skies","TS"),
    (19,"Wonders of Imagination","WI"),
    (20,"Phonics and Language 2","PL"),
    (20,"Phonics and Language 2 Tests",""),
    (21,"2nd Grade Writing Tablet","WT"),
    (21,"Writing with Phonics 2","WP"),
    (21,"Cursive Formation Flashcards","CFF"),
    (22,"Arithmetic 2","AR"),
    (22,"Arithmetic 2 Tests / Speed Drils",""),
    (23,"Across the Meadow","AM"),
    (23,"All Kinds of Animals","AKA"),
    (23,"Fun with Friends","FF"),
    (23,"Growing Up around the World","GAW"),
    (23,"Growing Up in Early America","GEA"),
    (23,"Growing Up Where Jesus Lived","GJL"),
    (23,"Handbook for Reading","HR"),
    (23,"My New Name","MN"),
    (23,"Primary Bible Reader","PBR"),
    (23,"Quests for Adventure","QA"),
    (23,"Reading Comprehension 2 Skill Sheets","RC2"),
    (23,"Through the Skies","TS"),
    (23,"Wonders of Imagination","WI"),
    (24,"Across the Meadow","AM"),
    (24,"All Kinds of Animals","AKA"),
    (24,"Fun with Friends","FF"),
    (24,"Growing Up around the World","GAW"),
    (24,"Growing Up in Early America","GEA"),
    (24,"Growing Up Where Jesus Lived","GJL"),
    (24,"Handbook for Reading","HR"),
    (24,"My New Name","MN"),
    (24,"Primary Bible Reader","PBR"),
    (24,"Quests for Adventure","QA"),
    (24,"Reading Comprehension 2 Skill Sheets","RC2"),
    (24,"Through the Skies","TS"),
    (24,"Wonders of Imagination","WI"),
    (25,"Across the Meadow","AM"),
    (25,"All Kinds of Animals","AKA"),
    (25,"Fun with Friends","FF"),
    (25,"Growing Up around the World","GAW"),
    (25,"Growing Up in Early America","GEA"),
    (25,"Growing Up Where Jesus Lived","GJL"),
    (25,"Handbook for Reading","HR"),
    (25,"My New Name","MN"),
    (25,"Primary Bible Reader","PBR"),
    (25,"Quests for Adventure","QA"),
    (25,"Reading Comprehension 2 Skill Sheets","RC2"),
    (25,"Through the Skies","TS"),
    (25,"Wonders of Imagination","WI"),
    (26,"Spelling and Poetry 2","SP"),
    (28,"Art Projects 2","AP"),
    (28,"Enjoying God's World","EGW"),
    (28,"Health, Safety, and Manners 2","HSM"),
    (28,"Our America","OA");